### PR TITLE
docs: add website to list of Showcase

### PR DESCRIPTION
**Pull request by lyqht**

### CODE REVIEW

**Comment by jpedroschmitz** [comment]
Do you have it deployed to production? @lyqht

**Comment by jpedroschmitz** [comment]
Do you have a link to the website? I want to keep the domain on the left, something like:
```
[unfork.com](https://unfork.com)
```

**Comment by lyqht** [comment]
hi @jpedroschmitz, i have modified it. thanks!

**Review by jpedroschmitz — APPROVED** [review]

**Comment by jpedroschmitz** [comment]
Thanks a lot, @lyqht!

**Pull request merged**
