### PR TITLE
chore(deps): update dependency husky to v5.0.9

### PR DESCRIPTION
**Pull request by kuasha420**
Update to the next major version of husky as it is promored to latest tag on npm. Also migrated all hooks to new system. Removed/edited out old configurations from package json. 

Let me know if anything else needs changing.

### CODE REVIEW

**Comment by jpedroschmitz** [comment]
Hey @kuasha420, thanks for the PR!

I am going to take a look soon 💜

**Review by jpedroschmitz — CHANGES_REQUESTED** [review]
Hey @kuasha420, great job! Everything is working fine =D

I'll request just a small update to support yarn on Windows (maybe someone will be using it).

The link below show's how to fix this issue:

https://typicode.github.io/husky/#/?id=yarn-on-windows

**Comment by kuasha420** [comment]
Thanks for the review. I just followed your provided link and added windows support. Couldn't verify whether it's working on Windows though as I don't have any Windows machine or VM set up at this moment.

Regards.

**Review by jpedroschmitz — APPROVED** [review]
Yeh, I also don't have a way to test it out, but I believe it will work correctly 🚀 

Thanks again!

**Pull request merged**
